import type { DashboardData } from './types';

// Local-only demo fallback shown when generated dashboard data is unavailable.
// The dashboard labels this state as "示例数据" so it cannot be mistaken for source records.
export const demoFallbackData: DashboardData = {
  generatedAt: 'not generated yet',
  health: 'warning',
  counts: {
    claims: 1,
    experiments: 1,
    datasets: 1,
    figures: 1,
    sections: 1,
    graphNodes: 5,
    graphEdges: 4,
    skillIssues: 0,
    citationSuggestions: 0,
    pluginRecommendations: 1,
  },
  currentStatus: {
    'Current stage': '1-12/待填写',
    'Active focus': '规划/文献/实验/写作/终审/待填写',
    'Current audit tier': 'quick/advisor/final/TBD',
    'Main blocker': '请先运行 pnpm run prepare:data 生成真实数据',
    'Next concrete action': '运行工作流健康检查',
  },
  currentWorkspaceSummary: {
    stage: '1-12/待填写',
    focus: '规划/文献/实验/写作/终审/待填写',
    blocker: '请先运行 pnpm run prepare:data 生成真实数据',
    nextAction: '运行工作流健康检查',
    auditTier: 'quick/advisor/final/TBD',
    evidenceGapCount: 1,
    recentExperiment: 'EXP-001 · planned',
  },
  nextRecommendations: [
    '建议：运行刷新检查，生成真实 Dashboard 数据。',
    '建议：设置当前阶段，然后只处理该阶段的关键文件和阻塞项。',
  ],
  activeStageWorkspace: {
    stage: '',
    name: '选择阶段',
    fileKeys: ['dashboard', 'dailyWorkflowEntry'],
    commands: ['python scripts/research_workflow_doctor.py --warn-only'],
    recommendedActions: ['先设置当前阶段，再查看本阶段推荐动作。'],
    issues: { p0: [], p1: ['尚未生成真实 dashboard 数据。'] },
  },
  stages: [
    { stage: '1', name: '论文规划', status: 'pending', record: 'thesis-brief.md', notes: '' },
    { stage: '2', name: '文献发现与综述', status: 'pending', record: 'literature-matrix.md', notes: '' },
    { stage: '3', name: '实验问题定义', status: 'pending', record: 'claim-evidence-map.md', notes: '' },
    { stage: '4', name: '实验架构规划', status: 'pending', record: 'experiment-architecture.md', notes: '' },
    { stage: '5', name: '科研代码实现', status: 'pending', record: 'git-version-log.md', notes: '' },
    { stage: '6', name: '实验运行与监控', status: 'pending', record: 'experiment-runbook.md', notes: '' },
    { stage: '7', name: '实验记录与结果扫描', status: 'pending', record: 'experiment-registry.md', notes: '' },
    { stage: '8', name: '结果分析与论点映射', status: 'pending', record: 'claim-evidence-map.md', notes: '' },
    { stage: '9', name: '图表与模型结构图制作', status: 'pending', record: 'figure-plan.md', notes: '' },
    { stage: '10', name: '论文写作与润色', status: 'pending', record: 'writing-outline.md', notes: '' },
    { stage: '11', name: '笔记本 DOCX / 可选 LaTeX / PDF', status: 'pending', record: 'final artifacts', notes: '' },
    { stage: '12', name: '笔记本终审与答辩准备', status: 'pending', record: 'final-audit.md', notes: '' },
  ],
  issues: {
    p0: [],
    p1: ['尚未生成真实 dashboard 数据。'],
  },
  summary: '示例数据',
  recentExperiments: [{ id: 'EXP-001', status: 'planned', output: 'outputs/EXP-001' }],
  experimentReports: [],
  citationSuggestions: [],
  sectionCitationCoverage: [
    {
      sectionId: 'SEC-INTRO-001',
      segmentId: 'SEG-INTRO-001',
      strong: 'missing',
      partial: 'candidate',
      background: 'verified',
      contradictory: 'missing',
      zoteroChecked: 'missing',
      readerChecked: 'candidate',
      status: 'candidate',
      candidateReferences: '示例候选论文',
      identifiers: 'DOI:TBD',
      zoteroStatus: '待加入 Zotero',
      readerStatus: '待 Reader/Scite 检查',
      nextAction: '确认 strong support 文献后写入正式引用表',
    },
  ],
  citationCoverageSummary: {
    missingStrong: 1,
    candidate: 1,
    verified: 0,
    risk: 0,
  },
  pluginRecommendations: [
    {
      plugin: 'Build Web Apps',
      stage: 'TBD',
      reason: '示例数据：Dashboard 前端改动需要构建和浏览器检查。',
      action: '运行 pnpm run build，并用浏览器检查首屏、按钮和移动端。',
      record: 'docs/thesis/dashboard-ux-qa.md',
      required: false,
      level: 'recommended',
      status: 'recommended',
    },
  ],
  pluginGateHealth: {
    missingPolicy: false,
    missingReviewLog: false,
    pendingRequiredGates: 0,
    optionalSuggestions: 1,
  },
  handoffPackage: {
    exists: 'false',
    latestZip: '',
    latestDir: '',
    verifyReport: '',
  },
  skillHealth: {
    totalSkills: 0,
    metadataIssues: 0,
    metadataWarnings: 0,
    brokenReferences: 0,
    missingScripts: 0,
    outdatedAssumptions: 0,
  },
  records: {
    claims: [{ id: 'CLM-001', status: 'missing', experiments: 'EXP-001', figures: 'FIG-001' }],
    experiments: [{ id: 'EXP-001', status: 'planned', output: 'outputs/EXP-001' }],
    datasets: [{ id: 'DATA-001', status: 'missing', hash: 'TBD', access: 'TBD' }],
    figures: [{ id: 'FIG-001', status: 'planned' }],
    sections: [{ id: 'SEC-INTRO-001', coverage: 'missing' }],
  },
  graph: {
    nodes: [
      { id: 'SEC-INTRO-001', kind: 'SEC', label: 'SEC-INTRO-001' },
      { id: 'CLM-001', kind: 'CLM', label: 'CLM-001' },
      { id: 'EXP-001', kind: 'EXP', label: 'EXP-001' },
      { id: 'DATA-001', kind: 'DATA', label: 'DATA-001' },
      { id: 'FIG-001', kind: 'FIG', label: 'FIG-001' },
    ],
    edges: [
      { source: 'SEC-INTRO-001', target: 'CLM-001', relation: 'contains_claim' },
      { source: 'CLM-001', target: 'EXP-001', relation: 'supported_by' },
      { source: 'CLM-001', target: 'DATA-001', relation: 'traces_to' },
      { source: 'FIG-001', target: 'CLM-001', relation: 'visualizes' },
    ],
  },
  focusedEvidenceGraph: {
    nodes: [
      { id: 'SEC-INTRO-001', kind: 'SEC', label: 'SEC-INTRO-001' },
      { id: 'CLM-001', kind: 'CLM', label: 'CLM-001' },
      { id: 'EXP-001', kind: 'EXP', label: 'EXP-001' },
      { id: 'DATA-001', kind: 'DATA', label: 'DATA-001' },
      { id: 'FIG-001', kind: 'FIG', label: 'FIG-001' },
    ],
    edges: [
      { source: 'SEC-INTRO-001', target: 'CLM-001', relation: 'contains_claim' },
      { source: 'CLM-001', target: 'EXP-001', relation: 'supported_by' },
      { source: 'CLM-001', target: 'DATA-001', relation: 'traces_to' },
      { source: 'FIG-001', target: 'CLM-001', relation: 'visualizes' },
    ],
  },
  links: {
    dashboard: 'docs/thesis/workflow-dashboard.md',
    dailyWorkflowEntry: 'docs/thesis/daily-workflow-entry.md',
    sectionCitationMap: 'docs/thesis/section-citation-map.md',
    claimMap: 'docs/thesis/claim-evidence-map.md',
    pluginGatePolicy: 'docs/thesis/plugin-gate-policy.md',
    pluginReviewLog: 'docs/thesis/plugin-review-log.md',
    dashboardUxQa: 'docs/thesis/dashboard-ux-qa.md',
  },
};
